const KEYBOARD_ONFOCUS = 'KEYBOARD_ONFOCUS_'
const KEYBOARD_DIRECTION = 'KEYBOARD_DIRECTION_'
const KEYBOARD_ENTER = 'KEYBOARD_ENTER_'
const KEYBOARD_TAB = 'KEYBOARD_TAB_'

const KEYBOARD_ACTIONS_NAME = {
  ENTER: 'enter',
  TAB: 'tab',
  UP: 'up',
  DOWN: 'down',
  LEFT: 'left',
  RIGHT: 'right',
}

export { KEYBOARD_DIRECTION, KEYBOARD_ENTER, KEYBOARD_ONFOCUS, KEYBOARD_TAB, KEYBOARD_ACTIONS_NAME }
